% em_custom_settings_example
% example settings file for use for em_saccade_blink_detection
% see defpar in em_saccade_blink_detection.m for more options
% should contain variable **settings** as below!

settings = {...
	'SampleRate',500,...
	'SacOnsetVelThr',2.5,...
	'SacOffsetVelThr',2.5,...
	'MinSacDuration',0.01,...
	'MaxSacDuration',Inf,...
	'PosSmoothConvWin','rectwin',...
	'PosSmoothConvLen',0,...
	'PosFilterCutoff',0,...
	'VelFilterCutoff',0,...
	'Plot',false,...
	'OpenFigure',false,...
	};